### ISSUE TITLE
Install script fails on "Pulling latest version from GitHub"

### ISSUE THREAD

**Issue by tetraptych** [bayesimpact/bayes-developer-setup#65]
`install.sh` fails on the "Pulling latest version from GitHub" step.

```
Creating /Users/brianlewis/.bayes-developer-setup
Pulling latest version from GitHub.

Error fetching statuses: Unauthorized (HTTP 401)
Bad credentials
Make sure you are signed into hub.
install.sh: line 115: ./common-installs/github_tools.sh: Permission denied
install.sh: line 119: ./common-installs/mac_setup.sh: Permission denied
```

Some notes:
- `.bashrc` is sourced in `.bash_profile`
- `which hub` returns `~/.bayes-developer-setup/bin/hub`
- Other `hub` commands run fine, e.g. `hub clone https://github.com/github/hub`. This is true even with private repositories, suggesting that hub has valid OAuth credentials.

**Comment by tetraptych** [comment]
Note: running `hub ci-status` and logging into hub independent from the install script resolves this issue, since afterward `bash install.sh` works as intended.

**Comment by ericboucher** [comment]
Added user interaction if shell is interactive, suggesting user is running script for the first time.
